package tallyexport

import (
	"strings"
	"text/template"
)

// xmlEscape replaces the 5 XML special characters with their entity references.
func xmlEscape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	s = strings.ReplaceAll(s, "'", "&apos;")
	return s
}

var tallyTemplate *template.Template

func init() {
	funcMap := template.FuncMap{
		"xmlEscape": xmlEscape,
	}
	tallyTemplate = template.Must(template.New("tally").Funcs(funcMap).Parse(tallyXML))
}

const tallyXML = `<ENVELOPE>
<HEADER>
<TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
<BODY>
<IMPORTDATA>
<REQUESTDESC>
<REPORTNAME>Vouchers</REPORTNAME>
<STATICVARIABLES>
<SVCURRENTCOMPANY>{{.CompanyName | xmlEscape}}</SVCURRENTCOMPANY>
</STATICVARIABLES>
</REQUESTDESC>
<REQUESTDATA>
{{- range .Vouchers}}
<TALLYMESSAGE xmlns:UDF="TallyUDF">
<VOUCHER REMOTEID="{{.RemoteID}}" VCHKEY="" VCHTYPE="Purchase" ACTION="Create" OBJVIEW="Invoice Voucher View">
<ADDRESS.LIST TYPE="String"><ADDRESS></ADDRESS><ADDRESS></ADDRESS><ADDRESS></ADDRESS></ADDRESS.LIST>
<BASICBUYERADDRESS.LIST TYPE="String"><BASICBUYERADDRESS></BASICBUYERADDRESS><BASICBUYERADDRESS></BASICBUYERADDRESS><BASICBUYERADDRESS></BASICBUYERADDRESS></BASICBUYERADDRESS.LIST>
<BASICORDERTERMS.LIST TYPE="String"><BASICORDERTERMS></BASICORDERTERMS></BASICORDERTERMS.LIST>
<OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>
<DATE>{{.Date}}</DATE>
<REFERENCEDATE>19000101</REFERENCEDATE>
<GUID/>
<STATENAME></STATENAME>
<GSTREGISTRATIONTYPE>{{.GSTRegType}}</GSTREGISTRATIONTYPE>
<NARRATION>{{.Narration | xmlEscape}}</NARRATION>
<COUNTRYOFRESIDENCE></COUNTRYOFRESIDENCE>
<PARTYGSTIN>{{.PartyGSTIN}}</PARTYGSTIN>
<TAXUNITNAME/>
<PARTYNAME>{{.PartyName | xmlEscape}}</PARTYNAME>
<VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>
<REFERENCE>{{.Reference | xmlEscape}}</REFERENCE>
<VOUCHERNUMBER>{{.VoucherNumber | xmlEscape}}</VOUCHERNUMBER>
<PARTYLEDGERNAME>{{.PartyName | xmlEscape}}</PARTYLEDGERNAME>
<PARTYPINCODE></PARTYPINCODE>
<BASICBASEPARTYNAME>{{.PartyName | xmlEscape}}</BASICBASEPARTYNAME>
<CSTFORMISSUETYPE/>
<CSTFORMRECVTYPE/>
<CONSIGNEEGSTIN></CONSIGNEEGSTIN>
<CONSIGNEEMAILINGNAME></CONSIGNEEMAILINGNAME>
<CONSIGNEESTATENAME></CONSIGNEESTATENAME>
<CONSIGNEEPINCODE></CONSIGNEEPINCODE>
<BUYERSCSTNUMBER></BUYERSCSTNUMBER>
<FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
<PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
<PLACEOFSUPPLY>{{.PlaceOfSupply | xmlEscape}}</PLACEOFSUPPLY>
<TYPEOFEXCISEVOUCHER></TYPEOFEXCISEVOUCHER>
<BASICSHIPPEDBY></BASICSHIPPEDBY>
<BASICBUYERNAME></BASICBUYERNAME>
<BASICORDERREF></BASICORDERREF>
<BASICSHIPDOCUMENTNO></BASICSHIPDOCUMENTNO>
<BASICFINALDESTINATION></BASICFINALDESTINATION>
<BASICBUYERSSALESTAXNO></BASICBUYERSSALESTAXNO>
<BASICDUEDATEOFPYMT></BASICDUEDATEOFPYMT>
<BASICDATETIMEOFINVOICE>{{.DateOfInvoice}}</BASICDATETIMEOFINVOICE>
<BASICDATETIMEOFREMOVAL>{{.DateOfInvoice}}</BASICDATETIMEOFREMOVAL>
<VCHGSTCLASS/>
<COSTCENTRENAME></COSTCENTRENAME>
<VOUCHERTYPEORIGNAME>Purchase</VOUCHERTYPEORIGNAME>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<ISMSTFROMSYNC>No</ISMSTFROMSYNC>
<ASORIGINAL>No</ASORIGINAL>
<AUDITED>No</AUDITED>
<FORJOBCOSTING>No</FORJOBCOSTING>
<ISOPTIONAL>No</ISOPTIONAL>
<EFFECTIVEDATE>{{.Date}}</EFFECTIVEDATE>
<USEFOREXCISE>No</USEFOREXCISE>
<ISFORJOBWORKIN>No</ISFORJOBWORKIN>
<ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
<USEFORINTEREST>No</USEFORINTEREST>
<USEFORGAINLOSS>No</USEFORGAINLOSS>
<USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
<USEFORCOMPOUND>No</USEFORCOMPOUND>
<USEFORSERVICETAX>No</USEFORSERVICETAX>
<ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
<EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
<USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
<EXCISEOPENING>No</EXCISEOPENING>
<USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
<ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
<ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
<ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
<INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
<ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
<ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
<IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
<ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
<ISISDVOUCHER>No</ISISDVOUCHER>
<ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
<ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
<ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
<GSTNOTEXPORTED>No</GSTNOTEXPORTED>
<ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
<ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
<ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
<ISCANCELLED>No</ISCANCELLED>
<HASCASHFLOW>No</HASCASHFLOW>
<ISPOSTDATED>No</ISPOSTDATED>
<USETRACKINGNUMBER>No</USETRACKINGNUMBER>
<ISINVOICE>Yes</ISINVOICE>
<MFGJOURNAL>No</MFGJOURNAL>
<HASDISCOUNTS>No</HASDISCOUNTS>
<ASPAYSLIP>No</ASPAYSLIP>
<ISCOSTCENTRE>Yes</ISCOSTCENTRE>
<ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
<ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
<ISBLANKCHEQUE>No</ISBLANKCHEQUE>
<ISVOID>No</ISVOID>
<ISONHOLD>No</ISONHOLD>
<ORDERLINESTATUS>No</ORDERLINESTATUS>
<VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
<VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
<ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
<VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
<ISVATDUTYPAID>Yes</ISVATDUTYPAID>
<ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
<ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
<ISDELETED>No</ISDELETED>
<CHANGEVCHMODE>No</CHANGEVCHMODE>
<ALTERID></ALTERID>
<MASTERID></MASTERID>
<VOUCHERKEY></VOUCHERKEY>
<EXCLUDEDTAXATIONS.LIST></EXCLUDEDTAXATIONS.LIST>
<OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
<ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
<AUDITENTRIES.LIST></AUDITENTRIES.LIST>
<DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
<SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST>
<INVOICEDELNOTES.LIST>
<BASICSHIPPINGDATE>19000101</BASICSHIPPINGDATE>
<BASICSHIPDELIVERYNOTE></BASICSHIPDELIVERYNOTE>
</INVOICEDELNOTES.LIST>
<INVOICEINDENTLIST.LIST/>
<ATTENDANCEENTRIES.LIST/>
<ORIGINVOICEDETAILS.LIST/>
<INVOICEEXPORTLIST.LIST/>
<INVOICEORDERLIST.LIST>
<BASICORDERDATE>19000101</BASICORDERDATE>
<BASICPURCHASEORDERNO></BASICPURCHASEORDERNO>
</INVOICEORDERLIST.LIST>
<INVOICEINDENTLIST.LIST></INVOICEINDENTLIST.LIST>
<ATTENDANCEENTRIES.LIST></ATTENDANCEENTRIES.LIST>
<ORIGINVOICEDETAILS.LIST></ORIGINVOICEDETAILS.LIST>
<INVOICEEXPORTLIST.LIST></INVOICEEXPORTLIST.LIST>
{{- range .LedgerEntries}}
<LEDGERENTRIES.LIST>
<OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>
{{- if ne .TaxRate ""}}
<BASICRATEOFINVOICETAX.LIST TYPE="Number"><BASICRATEOFINVOICETAX>{{.TaxRate}}</BASICRATEOFINVOICETAX></BASICRATEOFINVOICETAX.LIST>
<ROUNDTYPE/>
{{- end}}
<LEDGERNAME>{{.LedgerName | xmlEscape}}</LEDGERNAME>
<GSTCLASS/>
<ISDEEMEDPOSITIVE>{{.IsDeemedPositive}}</ISDEEMEDPOSITIVE>
<LEDGERFROMITEM>No</LEDGERFROMITEM>
<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
<ISPARTYLEDGER>{{.IsPartyLedger}}</ISPARTYLEDGER>
<ISLASTDEEMEDPOSITIVE>{{if eq .IsDeemedPositive "Yes"}}Yes{{else}}No{{end}}</ISLASTDEEMEDPOSITIVE>
<AMOUNT>{{.Amount}}</AMOUNT>
{{- if eq .IsDeemedPositive "Yes"}}
<VATEXPAMOUNT>{{.Amount}}</VATEXPAMOUNT>
{{- end}}
<SERVICETAXDETAILS.LIST/>
<BANKALLOCATIONS.LIST/>
{{- if .HasBillAlloc}}
<BILLALLOCATIONS.LIST>
<NAME>{{.BillRef | xmlEscape}}</NAME>
<BILLCREDITPERIOD JD="46022" P=""></BILLCREDITPERIOD>
<BILLTYPE>New Ref</BILLTYPE>
<TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
<AMOUNT>{{.Amount}}</AMOUNT>
<INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
<STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST>
</BILLALLOCATIONS.LIST>
{{- else}}
{{- if ne .TaxRate ""}}
<SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST>
<CATEGORYALLOCATIONS.LIST></CATEGORYALLOCATIONS.LIST>
<BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST>
<BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST>
{{- end}}
{{- end}}
<INTERESTCOLLECTION.LIST/>
<OLDAUDITENTRIES.LIST/>
<ACCOUNTAUDITENTRIES.LIST/>
<AUDITENTRIES.LIST/>
<INPUTCRALLOCS.LIST/>
<DUTYHEADDETAILS.LIST/>
<EXCISEDUTYHEADDETAILS.LIST/>
{{- if ne .TaxRate ""}}
<RATEDETAILS.LIST><GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD><GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE></RATEDETAILS.LIST>
<RATEDETAILS.LIST><GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD><GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE></RATEDETAILS.LIST>
<RATEDETAILS.LIST><GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD><GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE></RATEDETAILS.LIST>
<RATEDETAILS.LIST><GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD><GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE></RATEDETAILS.LIST>
{{- else}}
<RATEDETAILS.LIST/>
{{- end}}
<SUMMARYALLOCS.LIST/>
<STPYMTDETAILS.LIST/>
<EXCISEPAYMENTALLOCATIONS.LIST/>
<TAXBILLALLOCATIONS.LIST/>
<TAXOBJECTALLOCATIONS.LIST/>
<TDSEXPENSEALLOCATIONS.LIST/>
<VATSTATUTORYDETAILS.LIST/>
<COSTTRACKALLOCATIONS.LIST/>
<REFVOUCHERDETAILS.LIST/>
<INVOICEWISEDETAILS.LIST/>
<VATITCDETAILS.LIST/>
<ADVANCETAXDETAILS.LIST/>
</LEDGERENTRIES.LIST>
{{- end}}
{{- range .InventoryEntries}}
<ALLINVENTORYENTRIES.LIST>
<BASICUSERDESCRIPTION.LIST TYPE="String"><BASICUSERDESCRIPTION></BASICUSERDESCRIPTION></BASICUSERDESCRIPTION.LIST>
<STOCKITEMNAME>{{.StockItemName | xmlEscape}}</STOCKITEMNAME>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
<ISAUTONEGATE>No</ISAUTONEGATE>
<ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
<ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
<ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
<ISPRIMARYITEM>No</ISPRIMARYITEM>
<ISSCRAP>No</ISSCRAP>
<RATE>{{.Rate}}</RATE>
<DISCOUNT></DISCOUNT>
<AMOUNT>{{.Amount}}</AMOUNT>
<ACTUALQTY>{{.ActualQty}}</ACTUALQTY>
<BILLEDQTY>{{.BilledQty}}</BILLEDQTY>
<BATCHALLOCATIONS.LIST>
<MFDON></MFDON>
<GODOWNNAME>{{.Godown | xmlEscape}}</GODOWNNAME>
<BATCHNAME>{{.BatchName | xmlEscape}}</BATCHNAME>
<DESTINATIONGODOWNNAME>{{.Godown | xmlEscape}}</DESTINATIONGODOWNNAME>
<INDENTNO/>
<ORDERNO></ORDERNO>
<ORDERDUEDATE JD="46021" P=""></ORDERDUEDATE>
<TRACKINGNUMBER/>
<DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
<AMOUNT>{{.Amount}}</AMOUNT>
<ACTUALQTY>{{.ActualQty}}</ACTUALQTY>
<BILLEDQTY>{{.BilledQty}}</BILLEDQTY>
<ADDITIONALDETAILS.LIST/>
<VOUCHERCOMPONENTLIST.LIST/>
</BATCHALLOCATIONS.LIST>
<ACCOUNTINGALLOCATIONS.LIST>
<OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>
<LEDGERNAME>{{.PurchaseLedger | xmlEscape}}</LEDGERNAME>
<GSTCLASS/>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<LEDGERFROMITEM>No</LEDGERFROMITEM>
<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
<ISPARTYLEDGER>No</ISPARTYLEDGER>
<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
<AMOUNT>{{.Amount}}</AMOUNT>
<SERVICETAXDETAILS.LIST/>
<BANKALLOCATIONS.LIST/>
<BILLALLOCATIONS.LIST/>
<INTERESTCOLLECTION.LIST/>
<OLDAUDITENTRIES.LIST/>
<ACCOUNTAUDITENTRIES.LIST/>
<AUDITENTRIES.LIST/>
<INPUTCRALLOCS.LIST/>
<DUTYHEADDETAILS.LIST/>
<EXCISEDUTYHEADDETAILS.LIST/>
<RATEDETAILS.LIST/>
<SUMMARYALLOCS.LIST/>
<STPYMTDETAILS.LIST/>
<EXCISEPAYMENTALLOCATIONS.LIST/>
<TAXBILLALLOCATIONS.LIST/>
<TAXOBJECTALLOCATIONS.LIST/>
<TDSEXPENSEALLOCATIONS.LIST/>
<VATSTATUTORYDETAILS.LIST/>
<COSTTRACKALLOCATIONS.LIST/>
<REFVOUCHERDETAILS.LIST/>
<INVOICEWISEDETAILS.LIST/>
<VATITCDETAILS.LIST/>
<ADVANCETAXDETAILS.LIST/>
</ACCOUNTINGALLOCATIONS.LIST>
<DUTYHEADDETAILS.LIST/>
<SUPPLEMENTARYDUTYHEADDETAILS.LIST/>
<TAXOBJECTALLOCATIONS.LIST/>
<REFVOUCHERDETAILS.LIST/>
<EXCISEALLOCATIONS.LIST/>
<EXPENSEALLOCATIONS.LIST/>
</ALLINVENTORYENTRIES.LIST>
{{- end}}
<PAYROLLMODEOFPAYMENT.LIST/>
<ATTDRECORDS.LIST/>
<TEMPGSTRATEDETAILS.LIST/>
</VOUCHER>
</TALLYMESSAGE>
{{- end}}
</REQUESTDATA>
</IMPORTDATA>
</BODY>
</ENVELOPE>`
