package domain

import "errors"

var (
	ErrNotFound                  = errors.New("resource not found")
	ErrUnauthorized              = errors.New("unauthorized")
	ErrForbidden                 = errors.New("forbidden")
	ErrInvalidCredentials        = errors.New("invalid credentials")
	ErrTenantInactive            = errors.New("tenant is inactive")
	ErrUserInactive              = errors.New("user is inactive")
	ErrUnsupportedFileType       = errors.New("unsupported file type")
	ErrFileTooLarge              = errors.New("file exceeds maximum allowed size")
	ErrDuplicateEmail            = errors.New("email already exists for this tenant")
	ErrDuplicateTenantSlug       = errors.New("tenant slug already exists")
	ErrUploadFailed              = errors.New("file upload to storage failed")
	ErrCollectionNotFound        = errors.New("collection not found")
	ErrCollectionPermDenied      = errors.New("insufficient collection permission")
	ErrDuplicateCollectionFile   = errors.New("file already exists in collection")
	ErrSelfPermissionRemoval     = errors.New("cannot remove own permission")
	ErrInvalidPermission         = errors.New("invalid collection permission")
	ErrDocumentNotFound          = errors.New("document not found")
	ErrDocumentAlreadyExists     = errors.New("document already exists for this file")
	ErrDocumentNotParsed         = errors.New("document has not been parsed yet")
	ErrValidationRuleNotFound    = errors.New("validation rule not found")
	ErrInsufficientRole          = errors.New("insufficient role for this action")
	ErrInvalidStructuredData     = errors.New("invalid structured data format")
	ErrQuotaExceeded             = errors.New("monthly document quota exceeded")
	ErrEmailNotVerified          = errors.New("email not verified")
	ErrPasswordResetTokenInvalid = errors.New("password reset token is invalid or expired")
	ErrSocialAuthTokenInvalid    = errors.New("social auth token is invalid or expired")
	ErrPasswordLoginNotAllowed   = errors.New("this account uses social login; password login is not available")
	ErrAssigneeCannotReview      = errors.New("assignee does not have review permission on this collection")
	ErrServiceAccountReview      = errors.New("service accounts cannot review or be assigned documents")
	ErrServiceAccountNotFound    = errors.New("service account not found")
	ErrAPIKeyInvalid             = errors.New("invalid API key")
	ErrAPIKeyRevoked             = errors.New("API key has been revoked")
	ErrInvitationPending         = errors.New("please accept your invitation before logging in")
	ErrInvitationTokenInvalid    = errors.New("invitation token is invalid or has already been used")
	ErrInvitationAlreadyAccepted = errors.New("invitation has already been accepted")
	ErrInvalidAllowedSender      = errors.New("invalid allowed sender entry")
	ErrAlreadyExists             = errors.New("resource already exists")
	ErrAgentNotFound             = errors.New("connector agent not found")
	ErrAgentAlreadyExists        = errors.New("connector agent already registered for this service account")
)
